-- EstéticaGYR V2 — Supabase schema
-- Rode este arquivo apenas em um projeto Supabase dedicado ao EstéticaGYR.

create table if not exists public.gyr_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  mood_goal text,
  focus text[] not null default '{}',
  daily_time text,
  style text,
  challenge text,
  goal text,
  profile_type text,
  profile_score integer not null default 0 check (profile_score between 0 and 100),
  plan text not null default 'free' check (plan in ('free','pro')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gyr_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mood smallint not null check (mood between 1 and 5),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.gyr_routine_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  routine_date date not null default current_date,
  task_key text not null,
  completed boolean not null default true,
  created_at timestamptz not null default now(),
  unique(user_id, routine_date, task_key)
);

create table if not exists public.gyr_chat_memory (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.gyr_profiles enable row level security;
alter table public.gyr_checkins enable row level security;
alter table public.gyr_routine_logs enable row level security;
alter table public.gyr_chat_memory enable row level security;

create policy "profiles_select_own" on public.gyr_profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "profiles_insert_own" on public.gyr_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "profiles_update_own" on public.gyr_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "profiles_delete_own" on public.gyr_profiles for delete to authenticated using ((select auth.uid()) = user_id);

create policy "checkins_select_own" on public.gyr_checkins for select to authenticated using ((select auth.uid()) = user_id);
create policy "checkins_insert_own" on public.gyr_checkins for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "checkins_update_own" on public.gyr_checkins for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "checkins_delete_own" on public.gyr_checkins for delete to authenticated using ((select auth.uid()) = user_id);

create policy "routine_select_own" on public.gyr_routine_logs for select to authenticated using ((select auth.uid()) = user_id);
create policy "routine_insert_own" on public.gyr_routine_logs for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "routine_update_own" on public.gyr_routine_logs for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "routine_delete_own" on public.gyr_routine_logs for delete to authenticated using ((select auth.uid()) = user_id);

create policy "chat_select_own" on public.gyr_chat_memory for select to authenticated using ((select auth.uid()) = user_id);
create policy "chat_insert_own" on public.gyr_chat_memory for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "chat_delete_own" on public.gyr_chat_memory for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.gyr_profiles from anon;
revoke all on table public.gyr_checkins from anon;
revoke all on table public.gyr_routine_logs from anon;
revoke all on table public.gyr_chat_memory from anon;

grant select, insert, update, delete on table public.gyr_profiles to authenticated;
grant select, insert, update, delete on table public.gyr_checkins to authenticated;
grant select, insert, update, delete on table public.gyr_routine_logs to authenticated;
grant select, insert, delete on table public.gyr_chat_memory to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create index if not exists gyr_checkins_user_created_idx on public.gyr_checkins(user_id, created_at desc);
create index if not exists gyr_routine_user_date_idx on public.gyr_routine_logs(user_id, routine_date desc);
create index if not exists gyr_chat_user_created_idx on public.gyr_chat_memory(user_id, created_at desc);